#!/bin/bash

all_name='[ALL]'
mode=library

controls="󰐎 toggle
 play
 pause
󰒭 next
󰒮 prev
󰒟 random
󰕇 repeat"

make_status() {
    local nowplaying=$(mpc status | head -n1)
    local random_status=$(mpc status | tail -n1 | grep -Eo "random: (on|off)" | cut -d':' -f2 | xargs)
    local repeat_status=$(mpc status | tail -n1 | grep -Eo "repeat: (on|off)" | cut -d':' -f2 | xargs)
    local status_status=$(mpc status | head -n2 | tail -n1 | grep -Eo "\[\w+\]")
    local random=$([ "$random_status" == "on" ] && echo "󰒝" || echo "󰒞")
    local repeat=$([ "$repeat_status" == "on" ] && echo "󰑖" || echo "󰑗")
    local status=$([ "$status_status" == "[playing]" ] && echo "" || echo "")

    printf "$status $random $repeat $nowplaying"
}

d_artist() {
    mpc list artist | sort -f | dmenu -p "artist > " "${dmenu_args[@]}"
}

d_album() {
    local artist="$1"
    local albums

    mapfile -t albums < <(mpc list album artist "$artist")
    if (( ${#albums[@]} > 1 )) ; then
        {
            printf '%s\n' "$all_name"
            printf '%s\n' "${albums[@]}" | sort -f
        } | dmenu -p "albums by $artist > " "${dmenu_args[@]}"
    else
        # We only have one album, so just use that.
        printf '%s\n' "${albums[0]}"
    fi
}

d_playlist() {
    local format="%position% %title% \[%time%\]"
    local extra_format="(%artist% - %album%)"
    local track
    local num_extras

    # If all tracks are from the same artist and album, no need to display that
    num_extras=$(mpc playlist -f "$extra_format" | sort | uniq | wc -l)
    (( num_extras == 1 )) || format+=" $extra_format"

    track=$(mpc playlist -f "$format" | dmenu -p "$(make_status) > " "${dmenu_args[@]}")
    printf '%s' "${track%% *}"
}

d_control() {
    printf "${controls[@]}" | dmenu -p "$(make_status) > " "${dmenu_args[@]}" | cut -d' ' -f2
}

i=2

for arg do
    if [[ $arg == :: ]]; then
        dmenu_args=( "${@:$i}" )
        break
    fi

    case "$arg" in
        -l) mode=library ;;
        -p) mode=playlist ;;
        -c) mode=control ;;
    esac

    let i++
done

case "$mode" in
    library)
        artist=$(d_artist)
        [[ $artist ]] || exit 1

        album=$(d_album "$artist")
        [[ $album ]] || exit 2

        mpc clear
        if [[ $album == "$all_name" ]]; then
            mpc find artist "$artist" | sort | mpc add
        else
            mpc find artist "$artist" album "$album" | sort | mpc add
        fi

        mpc play >/dev/null
    ;;
    playlist)
        mpc play "$(d_playlist)" >/dev/null
    ;;
    control)
        control=$(d_control)
        [[ $control ]] || exit 1
        mpc "$(control)" >/dev/null
    ;;
esac
